
<SignOnPage>:
    name: "SignOnPage"

    
    MDBoxLayout:
        id: boxLayoutAllScreen
        orientation: 'vertical'
        padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)

        ScrollViewCustom:

            MDGridLayout:
                cols: 1

                size_hint_y: None
                height: self.minimum_height
                padding: dp(16), dp(16), dp(16),  dp(8)

                padding: dp(100 - root.manager.parent.parent.ids.toolbar.height)

                MDLabel:
                    text: 'REGISTRAR CUENTA'
                    font_style: "H3"
                    halign: 'center'
                    adaptive_height: True
                
                MDGridLayout:
                    cols: 1
                    padding: dp(50)
                    spacing: dp(20)
                    adaptive_height: True

                    MDTextField:
                        id: usernameSignOn
                        icon_left: "account"
                        hint_text: 'Escribir nombre de usuario'
                        mode: 'rectangle'
                        required: True

                    MDTextField:
                        id: emailSignOn
                        icon_left: "email"
                        hint_text: 'Escribir correo electrónico'
                        mode: 'rectangle'
                        validator: "email"
                        required: True

                    MDTextField:
                        id: passwordSignOn
                        icon_left: "account-key"
                        hint_text: 'Escribir contraseña'
                        mode: 'rectangle'
                        password: True
                        required: True
                        max_text_length: 5
                    
                    MDTextField:
                        id: repeatPasswordSignOn
                        icon_left: "account-key"
                        hint_text: 'Repetir contraseña'
                        mode: 'rectangle'
                        password: True
                        required: True
                        max_text_length: 5
                
                MDGridLayout:
                    cols: 3
                    spacing: dp(20)
                    adaptive_height: True
                    padding: dp(16), dp(32), dp(16), dp(8)

                    MDRectangleFlatButton:
                        text: 'Iniciar sesión'
                        font_style: 'H5'
                        size_hint_x: 0.4

                        on_release: root.ChangePageToSignIn()

                    MDLabel:
                        size_hint_x: 0.1

                    MDRaisedButton:
                        text: 'Enviar'
                        font_style: 'H5'
                        size_hint_x: 0.4

                        on_release: root.CreateAccount(root.ids.usernameSignOn.text, root.ids.emailSignOn.text, root.ids.passwordSignOn.text, root.ids.repeatPasswordSignOn.text)

