##: import RecycleViewTable templates.table.table
#:include templates/table/table.kv

#TOOLBAR
<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: "#e7e4c0"
    text_color: "#4a4939"
    icon_color: "#4a4939"
    ripple_color: "#c5bdd2"
    selected_color: "#0c6c4d"


#TOOLBAR
<DrawerLabelItem@MDNavigationDrawerItem>
    text_color: "#4a4939"
    icon_color: "#4a4939"
    focus_behavior: False
    selected_color: "#4a4939"
    _no_ripple_effect: True

#MENU SLICE
<ContentNavigationDrawer>

    MDNavigationDrawerMenu:

        MDNavigationDrawerHeader:
            title: "BroxElt S.A."
            title_color: "#4a4939"
            text: "Bienvenido XXXXX"
            source: "images/logo.jpg"
            spacing: "4dp"
            padding: "12dp", 0, 0, "40dp"

        MDNavigationDrawerLabel:
            text: "General"

        MDNavigationDrawerDivider:
            padding: dp(10),0, dp(12), dp(1)

        DrawerClickableItem:
            icon: "home"
            text_right_color: "#4a4939"
            text: "Panel de control"

            on_press:
                root.screen_manager.current = "InitialPage"

                app.root.ids.toolbar.title = self.text

        DrawerClickableItem:
            icon: "cash-register"
            text_right_color: "#4a4939"
            text: "Cajero"

            on_press:
                root.screen_manager.current = "CashierPage"

                app.root.ids.toolbar.title = self.text

        DrawerClickableItem:
            icon: "store"
            text_right_color: "#4a4939"
            text: "Almacen"
            on_press:
                root.screen_manager.current = "StorePage"

                app.root.ids.toolbar.title = self.text
        
        
        DrawerClickableItem:
            icon: "account-cash"
            text_right_color: "#4a4939"
            text: "Cliente"
            on_press:
                root.screen_manager.current = "ClientsPage"

                app.root.ids.toolbar.title = self.text               

        MDNavigationDrawerLabel:
            text: "Administrador"
            padding: dp(16), dp(10), dp(12), dp(10)


        MDNavigationDrawerDivider:
            padding: dp(10), 0, dp(12), dp(1)

        DrawerClickableItem:
            icon: "cube-send"
            text_right_color: "#4a4939"
            text: "Encargos"

            on_press:
                root.screen_manager.current = "ChargePage"

                app.root.ids.toolbar.title = self.text

        DrawerClickableItem:
            icon: "cash-multiple"
            text_right_color: "#4a4939"
            text: "Divisas"

            on_press:
                root.screen_manager.current = "ForeignExchangePage"

                app.root.ids.toolbar.title = self.text

        DrawerClickableItem:
            icon: "account-multiple"
            text_right_color: "#4a4939"
            text: "Proveedores"

            on_press:
                root.screen_manager.current = "SupplierPage"

                app.root.ids.toolbar.title = self.text
        
        DrawerClickableItem:
            icon: "cash-remove"
            text_right_color: "#4a4939"
            text: "Prestamos"

            on_press:
                root.screen_manager.current = "LoanPage"

                app.root.ids.toolbar.title = self.text

        DrawerClickableItem:
            icon: "receipt-text-clock"
            text_right_color: "#4a4939"
            text: "Historial de Ventas"

            on_press:
                root.screen_manager.current = "SalesHistoryPage"

                app.root.ids.toolbar.title = self.text
        
        DrawerClickableItem:
            icon: "text-box-search"
            text_right_color: "#4a4939"
            text: "Historial de Dinero"

            on_press:
                root.screen_manager.current = "MoneyHistory"

                app.root.ids.toolbar.title = self.text


                
        MDNavigationDrawerLabel:
            text: "Configuraciones"
            padding: dp(16), dp(10), dp(12), dp(10)

        MDNavigationDrawerDivider:
            padding: dp(10), 0, dp(12), dp(1)

        DrawerClickableItem:
            icon: "account-cog"
            text_right_color: "#4a4939"
            text: "Configuracion"

            on_press:
                root.screen_manager.current = "ConfigurationPage"

                app.root.ids.toolbar.title = self.text





HeaderAndFooter:

    orientation: "vertical"

    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager
            #Pagina de inicio
            SignIn:

            #Pagina de registrar cuenta
            SignOn:

            #Pagina de panel de control, o de inicio
            InitialPage:

            #Pagina del cajero
            CashierPage:
                
            #Pagina del almacen, junto con su pagina de modificacion y de elegir imagen en orden respectivamente
            StorePage:       
            StoreUpdatePage:
            ChooseImagePage:

            #Pagina de cliente
            ClientsPage:

            #Pagina de configuracion
            ConfigurationPage:

            #Pagina de divisas
            ForeignExchangePage:

            #Pagina de historial de ventas
            SalesHistoryPage:

            #Pagina de proveedores
            SupplierPage:
            SupplierUpdatePage:
            SupplierAddPage:

            #Pagina de Encargos
            ChargePage:

            #Pagina de historial de dinero
            MoneyHistory:

            #Pagina de prestamos
            LoanPage:
            LoanUpdatePage:
            LoanAddPage:


        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)
        
            ContentNavigationDrawer:
                screen_manager: screen_manager
                nav_drawer: nav_drawer


#CLASE Kivy que llama a la página "ChooseImage" para elegir imagen del producto
<ChooseImagePage>:
    name: "chooseimagePage"
    on_pre_enter: root.file_manager_open() #app.root.file_manager_open()

<InitialPage>:
    name: "InitialPage"

    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        MDGridLayout:
            cols: 1

            

            padding: dp(0), dp(root.manager.parent.parent.ids.toolbar.height), dp(0), dp(root.manager.parent.parent.ids.toolbarbottom.height)
            MDBoxLayout:
                adaptive_height: True               
                size_hint: 1, 1

                MDGridLayout:
                    cols: 1                                
                    
                    #DATOS
                    MDLabel:
                        markup: True
                        padding: dp(50), dp(20), dp(16), dp(1)
                        text: "[b][i]Datos[/i][/b]"

                        halign: "left"
                        font_style: "H3"
                        adaptive_height: True       

                    #DATOS DE USUARIO
                    MDBoxLayout:
                        orientation: 'horizontal'
                        #size_hint: 1, None
                        #height:75


                        MDGridLayout:
                        
                            cols: 2                             
                            padding: dp(1), dp(1), dp(1), dp(1)


                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "account"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        
                                    MDTextField:
                                        text: "123aaaaa"
                                        hint_text: "123123:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "account-hard-hat"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        
                                    MDTextField:
                                        text: "root"
                                        hint_text: "Nivel de usuario:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4


                    #CUENTAS
                    MDLabel:                                
                        markup: True
                        padding: dp(50), dp(1), dp(1), dp(1)
                        text: "[b][i]Cuenta[/i][/b]"
                        halign: "left"
                        font_style: "H3"
                        adaptive_height: True             

                    MDBoxLayout:
                        orientation: 'horizontal'
                        #size_hint: 1, None
                        #height:75

                        MDGridLayout:
                        
                            cols: 2                             
                            padding: dp(1), dp(1), dp(1), dp(1)


                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash-plus"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        

                                    
                                    MDTextField:
                                        text: "100$"
                                        hint_text: "Dinero Credito:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash-minus"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        
                                    MDTextField:
                                        text: "24$"
                                        hint_text: "Dinero prestado:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                    #DINERO DIVISAS
                    MDBoxLayout:
                        orientation: 'horizontal'
                        MDGridLayout:
                        
                            cols: 3                             
                            padding: dp(1), dp(1), dp(1), dp(1)


                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        

                                    
                                    MDTextField:
                                        text: "100$"
                                        hint_text: "Dinero en dólares:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash-minus"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        
                                    MDTextField:
                                        text: "24$"
                                        hint_text: "Dinero en pesos:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                            MDGridLayout:
                                cols: 2
                                adaptive_height: True

                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash-minus"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.05
                                        
                                    MDTextField:
                                        text: "24$"
                                        hint_text: "Dinero en bolívares:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                    #DINERO MENSUAL
                    MDBoxLayout:
                        orientation: 'horizontal'
                        MDGridLayout:
                        
                            cols: 1                             
                            padding: dp(1), dp(1), dp(1), dp(1)


                            MDGridLayout:
                                cols: 3
                                adaptive_height: True

                                MDLabel:
                                    size_hint_x: 0.2


                                MDGridLayout:
                                    adaptive_height: True
                                    cols: 4
                                    padding: dp(32), dp(1), dp(32), dp(16)
                                    size_hint_x: 0.8


                                    MDLabel:
                                        size_hint_x: 0.025


                                    MDIcon:
                                        padding: dp(1), dp(1), dp(1), dp(1)
                                        icon: "cash"
                                        font_size: '36sp' 
                                        size_hint_x: 0.4


                                    MDLabel:
                                        size_hint_x: 0.025
                                        

                                    
                                    MDTextField:
                                        text: "100$"
                                        hint_text: "Dinero en mensual:"
                                        mode: "rectangle"
                                        disabled: True 
                                        focus: True
                                        size_hint_x: 0.4

                            
                                MDLabel:
                                    size_hint_x: 0.2


<StoreUpdatePage>:
    name: "StorePageUpdate"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDScrollView:
            MDBoxLayout:

                orientation: 'horizontal'
                size_hint: 1, 1
                adaptive_height: True

                # LINEA O BORDE
                #canvas:
                #    Color:
                #        rgba: .1, .1, 1, .9
                #    Line:
                #        width: 2.
                #        rectangle: (self.x + 10, self.y - 10, self.width -20, self.height)
                        
                MDGridLayout:
                    cols: 1
                    padding: dp(16), dp(8)
                    size_hint_y: None
                    height: self.minimum_height  # required to size GridLayout

                            
                    MDGridLayout:
                        cols: 1
                        padding: dp(1), dp(32)

                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout

                        MDLabel:
                            text: "Cambiar Producto"
                            halign: "center"
                            font_style: "H4"

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(0), dp(16), dp(8) 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Nombre:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Nombre del producto"

                            required: True

                            helper_text_mode: "on_error"
                            helper_text: "Por favor, ingrese un nombre del producto." if len(self.text) == 0 else ""

                            max_text_length: 25
                            mode: "rectangle"
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Proveedor:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: inputSupplierMenu
                            size_hint_x: 0.7
                            #width: "375dp"
                            text: ""
                            hint_text: "Proveedor del producto"

                            required: True
                            readonly: True
                            
                            helper_text_mode: "on_error"
                            helper_text: "Por favor, ingrese un proveedor del producto." if len(self.text) == 0 else ""
                            mode: "rectangle"
                            
                            on_focus: if self.focus: app.MenuSupplierStore.open()
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1
                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Cantidad:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Cantidad del producto"

                            required: True

                            helper_text_mode: "on_error"
                            helper_text: "Por favor, ingrese la cantidad del producto." if len(self.text) == 0 else ""

                            max_text_length: 5
                            mode: "rectangle"
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Precio:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            width: "375dp"

                            hint_text: "Precio del producto"

                            required: True

                            helper_text_mode: "on_error"
                            helper_text: "Por favor, ingrese el precio del producto." if len(self.text) == 0 else ""

                            max_text_length: 10
                            mode: "rectangle"
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(16)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)
                            #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 

                            text: "Imagen:"
                            font_style: "H5"
                            halign: "right"

                        
                        MDRaisedButton:

                            #id: name_field
                            size_hint_x: 0.7
                            padding: dp(1), dp(1)
                            #width: "375dp"

                            #hint_text: "Imagen del producto"

                            required: True

                            #helper_text_mode: "on_error"
                            #helper_text: "Por favor, ingrese la imagen del producto." if len(self.text) == 0 else ""

                            #max_text_length: 10
                            #mode: "rectangle"
                            #line_color_normal: "red" if len(self.text) == 0 else "blue"

                            #on_press: app.root.file_manager_open() #app.root.file_manager_open()

                            text: "Elegir imagen" if len(imageProduct.source) == 0 else "Imagen elegida"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"

                            #OJO
                            on_press: root.manager.current = "chooseimagePage"
                            
                        
                        MDLabel:
                            size_hint_x: 0.1


                    MDGridLayout:

                        cols: 2

                        size_hint_y: None
                        padding: dp(80), dp(16), dp(98), dp(16)

                        height: root.height / 2  # required to size GridLayout

                        Label:
                        #    canvas.before:
                        #        Color: 
                        #            rgba: (1,0,1,1)
                        #        Rectangle:
                        #            size: self.size
                        #            pos: self.pos
                        FitImage:
                            id: imageProduct
                            source: "images/question.jpg"
                            #allow_stretch: True
                            #keep_ratio: False
                            size_hint_x: 1


                    MDGridLayout:
                        cols: 2
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        
                        height: self.minimum_height  # required to size GridLayout

                        MDRectangleFlatButton:
                            size_hint_x: 0.5
                            text: "Cancelar"
                            line_color: "red"
                            text_color: "red"

                        MDRaisedButton:
                            size_hint_x: 0.5
                            text: "Aceptar"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"

<StorePage>:
    name: "StorePage"

    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        MDGridLayout:
            cols: 1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
                    
            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(16), dp(16), dp(16)
                size_hint_y: None
                height: dp(root.manager.parent.parent.ids.toolbar.height)
                MDTextField:
                    id: ButtonMenuSearchingStore

                    size_hint_x: None
                    width: "100dp"

                    text: "TODO"
                    hint_text: "Tipo:"
                    icon_right: "arrow-down"

                    mode: "rectangle"
                    readonly: True 
                    focus: True

                    on_focus: if self.focus: root.CallbackMenuProduct(self)

                MDTextField:
                    id: SearchProduct
                    hint_text: 'Buscar producto'
                    icon_right: "android"
                    mode: "rectangle"

                MDFloatingActionButton:
                    id: ButtonSearchingStore
                    icon: "book-search"
                    style: "standard"
                    width: "100dp"
                    
            RecycleViewTable:

                id_table: "tableAlmacen"

                padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                objecto: self
                columnas: 5

                list_table_labels: ["id_imagen", "id_cedula", "id_proveedor", "id_cantidad", "id_precio"]
                list_table_data: ["imagen", "cedula", "proveedor", "cantidad", "precio"]

                modalData:
                    'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?", "Por favor, elija algunas de las opciones presentadas.", "Cancelar", "Eliminar", "Modificar",  lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete ("self","¿De verdad quiere eliminar este producto?", "Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")    ),lambda x: ModalsDialog.ChangePage("self", "StorePageUpdate", "Almacen - Modificar"))'

                test: 
                    'for i in range(1,20): d = {f"dato{i}": [f"images/logo.jpg", f"dato20_{i}_cedula", f"dato20_{i}_proveedor", f"dato20_{i}_cantidad", f"dato20_{i}_precio"]};self.objecto.DictionaryDataset.update(d)'

<ClientsPage>:
    name: "ClientsPage"

    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        MDGridLayout:
            cols: 1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
                    
            MDGridLayout:
                cols: 5
                spacing: dp(10)
                padding: dp(16), dp(16), dp(16), dp(16)
                size_hint_y: None
                height: dp(root.manager.parent.parent.ids.toolbar.height)
                MDTextField:
                    id: ButtonMenuSearchingClient

                    size_hint_x: None
                    width: "100dp"

                    text: "TODO"
                    hint_text: "Tipo:"
                    icon_right: "arrow-down"

                    mode: "rectangle"
                    readonly: True 
                    focus: True

                    on_focus: if self.focus: root.CallbackMenuClients(self)

                MDTextField:
                    id: SearchProduct
                    hint_text: 'Buscar cliente'
                    icon_right: "android"
                    mode: "rectangle"

                    size_hint_x: None
                    width: "400dp"

                MDFloatingActionButton:
                    id: ButtonSearchingClient

                    icon: "book-search"
                    type: "standard"

                MDLabel:

                MDFloatingActionButton:
                    icon: "account-multiple-plus"
                    type: "standard"

                    
            RecycleViewTable:
                id_table: "tableCliente"

                padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                objecto: self
                need_image: False
                columnas: 3

                list_table_labels: ["id_dado", "id_fecha", "id_monto"]
                list_table_data: ["dado por cliente", "fecha", "monto"]
                
                modalData: 
                    'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar a este cliente?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","StorePageUpdate", "Almacen - Modificar"))'
                
                test: 
                    'for i in range(1,5): d = {f"dato{i}": [f"dato_cliente{i}_dado", f"dato_cliente{i}_fecha", f"dato_cliente{i}_monto"]};self.objecto.DictionaryDataset.update(d)'

                
<HeaderAndFooter>:
    id: headerandfooter

    toolbar_object: toolbar

    toolbarbottom_object: toolbarbottom

    MDTopAppBar:
        id: toolbar
        pos_hint: {"top": 1}
        elevation: 4
        title: "Panel de Control"
        use_overflow: True
        left_action_items: [["menu", lambda x: root.ids.nav_drawer.set_state("open")]]
        right_action_items:
            [
            ["cash-100", lambda x: app.CallbackMenuChangeMoney(x), "Tipo de tasa - Dolar", "Tipo de tasa - Dolar"],
            ["weather-sunny", lambda x: app.CallbackModeScreen(x, 'oscuro'), "Modo Claro", "Modo Claro"],
            ["account-settings", lambda x: app.CallbackMenuUser(x), "Perfil" , "Perfil"],
            ]
            
    MDTopAppBar:
        id: toolbarbottom
        type_height: "small"
        headline_text: "Headline"
        title: "BroxElt S.A."
        elevation: 4
        anchor_title: "left"
        use_overflow: True
        
        right_action_items:
            [             
            ["account-cog", lambda x: app.callback(x), "", "Configuracion"],             
            ["cash-remove", lambda x: app.callback(x), "", "Prestamos"],             
            ["home", lambda x: app.ChangePage("InitialPage", "Panel de control"), "", "Panel de control"],    
            ["cash-register", lambda x: app.callback(x), "", "Cajero"],             
            ["store", lambda x: app.callback(x), "", "Almacen"],             
            ]


#PAGINA DE CAJERO

#####MODAL DE CASHIER PAGE

<ContentCashierPage>:
    
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    MDTextField:
        text: 'Producto Número 31'
        hint_text: 'Nombre del producto'
        mode: "rectangle"
        readonly: True


    MDTextField:
        text: '40'
        hint_text: 'Cantidad del producto'
        mode: "rectangle"

<CashierPage>:
    name: "CashierPage"

    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        
        
        MDGridLayout:
            cols:1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
            MDGridLayout:
                cols: 2
                #padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
                        
                    
                MDScrollView:

                    MDBoxLayout:

                        orientation: 'horizontal'
                        size_hint: 1, 1
                        adaptive_height: True
                        MDGridLayout:
                            cols: 1
                            padding: dp(16), dp(8)
                            size_hint_y: None
                            height: self.minimum_height  # required to size GridLayout


                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width - 15, self.height - 13

                            MDGridLayout:
                                cols: 1
                                padding: dp(1), dp(32), dp(1), dp(8)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout

                                MDLabel:
                                    text: "[b][i]Datos[/i][/b]"
                                    halign: "center"
                                    font_style: "H4"
                                    
                                    markup: True

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(12)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                    text: "Cédula:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDTextField:

                                    id: name_field
                                    size_hint_x: 0.4

                                    hint_text: "Cédula del cliente"

                                    required: True

                                    helper_text_mode: "on_error"
                                    helper_text: "Ingrese una cédula." if len(self.text) == 0 else ""

                                    max_text_length: 10
                                    mode: "rectangle"
                                    line_color_normal: "red" if len(self.text) == 0 else "blue"

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(12)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                    text: "Nombre:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDTextField:

                                    id: name_field
                                    size_hint_x: 0.4

                                    hint_text: "Nombre del cliente"

                                    required: True

                                    helper_text_mode: "on_error"
                                    helper_text: "Ingrese un nombre." if len(self.text) == 0 else ""

                                    max_text_length: 10
                                    mode: "rectangle"
                                    line_color_normal: "red" if len(self.text) == 0 else "blue"

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(12)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                    text: "Tipo de pago:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDTextField:

                                    id: ButtonMenuCashierPaymentType

                                    size_hint_x: 0.4
                                    text: "Dólar"
                                    icon_right: "arrow-down"

                                    mode: "rectangle"
                                    readonly: True 
                                    focus: True

                                    on_focus: if self.focus: root.CallbackMenuCashierPaymentType(self)

                            MDGridLayout:
                                cols: 3
                                spacing: dp(10)
                                padding: dp(16), dp(12), dp(1), dp(12)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                    text: "Pagado:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDTextField:

                                    id: name_field
                                    size_hint_x: 0.4

                                    text: "100$"
                                    readonly: True

                                    mode: "rectangle"

                                MDFloatingActionButton:

                                    size_hint_x: 0.2
                                    icon: "cash-plus"
                                    style: "standard"
                                    elevation: 0


                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(12)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                    text: "Costo total:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDTextField:

                                    id: name_field
                                    size_hint_x: 0.4

                                    text: "10$"
                                    readonly: True

                                    mode: "rectangle"
                            
                    

                MDBoxLayout:
                    orientation: 'vertical'
                    size_hint: 1, 1
                    padding: dp(1), dp(16), dp(1), dp(1)
                    #spacing: dp(-60)

                    canvas.before:
                        Color:
                            rgba: .5, .5, .5, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height - 13
                    MDGridLayout:
                        cols: 1
                                
                        MDGridLayout:
                            cols: 3
                            spacing: dp(20)
                            padding: dp(16), dp(16), dp(16), dp(16)
                            size_hint_y: None
                            height: dp(root.manager.parent.parent.ids.toolbar.height)
                            MDTextField:
                                id: ButtonMenuSearchingStore

                                size_hint_x: None
                                width: "100dp"

                                text: "TODO"
                                hint_text: "Tipo:"
                                icon_right: "arrow-down"

                                mode: "rectangle"
                                readonly: True 
                                focus: True

                                on_focus: if self.focus: root.CallbackMenuProduct(self)

                            MDTextField:
                                id: SearchProduct
                                hint_text: 'Buscar producto'
                                icon_right: "android"
                                mode: "rectangle"

                            MDFloatingActionButton:
                                id: ButtonSearchingStore
                                icon: "book-search"
                                style: "standard"
                                width: "100dp"
                                
                        RecycleViewTable:

                            id_table: "tableCajeroProducto"

                            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                            objecto: self
                            need_image: True
                            columnas: 5

                            list_table_labels: ["id_imagen", "id_cedula", "id_proveedor"]
                            list_table_data: ["imagen", "cedula", "proveedor"]

                            modalData: 
                                'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?", "Por favor, elija algunas de las opciones presentadas.", "", "Cancelar", "Agregar",  lambda x: print("click cancerlar"),       lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),        lambda x: ModalsDialog.ChangePage("self", "StorePageUpdate", "Almacen - Modificar"))'
                            
                            test: 
                                'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_cedula", f"dato{i}_proveedor"]};self.objecto.DictionaryDataset.update(d)'


            MDScrollView:
                MDGridLayout:
                    cols: 1
                    
                    #MDGridLayout:
                    #    cols: 1
                    #    padding: dp(8), dp(32), dp(8), dp(8)
                    size_hint_y: None
                    height: self.minimum_height


                    #    MDLabel:
                    #        text: "Proveedores"
                    #        halign: "center"
                    #        font_style: "H4"
                    
                    RecycleViewTable:
                    
                        id_table: "tableCashier"

                        size_hint_y: None
                        height: dp(400)
                        padding: dp(16), dp(16), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                        objecto: self
                        columnas: 5
                        need_image: True
                        
                        list_table_labels: ["id_imagen", "id_dado", "id_fecha", "id_monto"]
                        list_table_data: ["imagen","dado por", "fecha", "monto"]

                        modalData: 
                            'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",     lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),    lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este producto?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),     lambda x: ModalsDialog.ChangeAmountProductModal("self", "Cambiar cantidad del producto"))'

                        test: 
                            'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_dado", f"dato{i}_fecha", f"dato{i}_monto"]};self.objecto.DictionaryDataset.update(d)'


            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                MDBoxLayout:
                    pos_hint: {'center_x': .5}
                    orientation: "vertical"
                    adaptive_height: True

                    MDGridLayout:
                        padding: dp(10) 
                        cols: 3 
                        spacing: 10
                        size_hint: None, None
                        size: self.minimum_size
                        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                        MDRectangleFlatButton:
                            text: "Cancelar"
                            text_color: "red"
                            line_color: "red"


                        MDRaisedButton:
                            text: "Presupuesto"
                            text_color: "white"
                            md_bg_color: "green"

                        MDRaisedButton:
                            text: "Aceptar"
                            text_color: "white"
                            md_bg_color: "blue"


<ConfigurationPage>:
    name: "ConfigurationPage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDGridLayout:
            cols: 1
            padding: dp(16), dp(8)
                    
            MDGridLayout:
                cols: 1
                padding: dp(1), dp(32)

                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout

                MDLabel:
                    text: "Modificar datos de la cuenta"
                    halign: "center"
                    font_style: "H4"

            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(0), dp(16), dp(8) 
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Nombre:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: name_field
                    size_hint_x: 0.7
                    #width: "375dp"

                    hint_text: "Usuario actual"
                    text: "NOMBREDEUSUARIO"

                    mode: "rectangle"
                
                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.OpenModal("Usuario", "Repetir usuario", "dialogUsername", "Cambiar usuario")


            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(8)
                #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Correo:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: inputSupplierMenu
                    size_hint_x: 0.7

                    hint_text: "Correo electrónico actual"
                    text: "CORREODEPRUEBA@GMAIL.COM"

                    
                    mode: "rectangle"

                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.OpenModal("Correo electrónico", "Repetir correo electrónico", "dialogEmail", "Cambiar correo electrónico")

            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(8)
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Contraseña:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: name_field
                    size_hint_x: 0.7
                    #width: "375dp"

                    hint_text: "Contraseña actual"
                    text: "CONTRASEÑAACTUAL"

                    password: True
                    password_mask: "X"

                    mode: "rectangle"
                
                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.OpenModal("Contraseña", "Repetir contraseña", "dialogPassword", "Cambiar contraseña")


#####MODAL DE CONFIGURATION PAGE

<ContentConfigurationPage>:
    
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    MDTextField:
        id: inputOne
        hint_text: root.inputOne
        mode: "rectangle"


    MDTextField:
        id: inputTwo
        hint_text: root.inputTwo
        mode: "rectangle"


<ForeignExchangePage>:
    name: "ForeignExchangePage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDGridLayout:
            cols: 1
            padding: dp(16), dp(8)
                    
            MDGridLayout:
                cols: 1
                padding: dp(1), dp(32)

                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout

                MDLabel:
                    text: "Última actualización: 28-04-2024"
                    halign: "center"
                    font_style: "H4"

            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(0), dp(16), dp(8) 
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Dolar:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: name_field
                    size_hint_x: 0.7
                    #width: "375dp"

                    hint_text: "Tasa de dólares"
                    text: root.inputDollar

                    mode: "rectangle"
                    readonly: True
                
                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.ChangeForeignExchange("dolar")



            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(8)
                #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Pesos:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: inputSupplierMenu
                    size_hint_x: 0.7

                    hint_text: "Tasa de pesos"
                    text: root.inputPeso

                    
                    mode: "rectangle"
                    readonly: True

                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.ChangeForeignExchange("peso")


            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(8)
                size_hint_y: None
                height: self.minimum_height  # required to size GridLayout
                MDLabel:
                    size_hint_x: 0.38
                    #width: "250dp"
                    padding: dp(32), dp(1)

                    text: "Bolívar:"
                    halign: "right"
                    font_style: "H5"
                
                MDTextField:

                    id: name_field
                    size_hint_x: 0.7
                    #width: "375dp"

                    hint_text: "Tasa de bolívares"
                    text: root.inputBolivar

                    mode: "rectangle"
                    readonly: True
                
                MDFloatingActionButton:
                    size_hint_x: 0.1
                    
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.ChangeForeignExchange("bolivar")


#####MODAL DE CONFIGURATION PAGE

<ContentForeignExchangePage>:
    
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"

    MDTextField:
        id: inputOne
        hint_text: root.inputOne
        mode: "rectangle"


    MDTextField:
        id: inputTwo
        hint_text: root.inputTwo
        mode: "rectangle"

<SalesHistoryPage>:
    name: "SalesHistoryPage"

    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        MDGridLayout:
            cols: 1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
                    
            MDGridLayout:
                cols: 3
                spacing: dp(20)
                padding: dp(16), dp(16), dp(16), dp(16)
                size_hint_y: None
                height: dp(root.manager.parent.parent.ids.toolbar.height)
                MDTextField:
                    id: ButtonMenuSearchingSalesHistory

                    size_hint_x: None
                    width: "100dp"

                    text: "TODO"
                    hint_text: "Tipo:"
                    icon_right: "arrow-down"

                    mode: "rectangle"
                    readonly: True 
                    focus: True

                    on_focus: if self.focus: root.CallbackMenuSalesHistory(self)

                MDTextField:
                    id: SearchProduct
                    hint_text: 'Buscar historial de venta'
                    icon_right: "android"
                    mode: "rectangle"

                MDFloatingActionButton:
                    id: ButtonSearchingSalesHistory

                    width: "150dp"
                    icon: "book-search"
                    style: "standard"
                    width: "100dp"
                    
            RecycleViewTable:

                id_table: "tableSalesHistory"

                padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                need_image: True
                objecto: self
                columnas: 5

                list_table_labels: ["id_imagen", "id_cliente", "id_empleado", "id_monto", "id_fecha"]
                list_table_data: ["imagen","cliente", "empleado", "monto", "fecha"]

                modalData: 
                    'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este producto?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","StorePageUpdate", "Almacen - Modificar"))'
                
                test: 
                    'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_cliente", f"dato{i}_empleado", f"dato{i}_monto", f"dato{i}_fecha"]};self.objecto.DictionaryDataset.update(d)'
                

# PAGINA DE ENCARGO
<ChargePage>:
    name: "ChargePage"

    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)

        MDGridLayout:
            cols: 1
                        
            MDGridLayout:
                cols: 5
                spacing: dp(10)
                padding: dp(16), dp(16), dp(16), dp(16)
                size_hint_y: None
                height: dp(root.manager.parent.parent.ids.toolbar.height)
                MDTextField:
                    id: ButtonMenuSearchingCharge

                    size_hint_x: None
                    width: "100dp"

                    text: "TODO"
                    hint_text: "Tipo:"
                    icon_right: "arrow-down"

                    mode: "rectangle"
                    readonly: True 
                    focus: True

                    on_focus: if self.focus: root.CallbackMenuCharge(self)

                MDTextField:
                    id: SearchProduct
                    hint_text: 'Buscar encargo'
                    icon_right: "android"
                    mode: "rectangle"

                    size_hint_x: None
                    width: "400dp"

                MDFloatingActionButton:
                    id: ButtonSearchingCharge

                    icon: "book-search"
                    type: "standard"

                MDLabel:

                MDFloatingActionButton:
                    icon: "account-multiple-plus"
                    type: "standard"

            
            RecycleViewTable:

                id_table: "tableCharge"

                padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)
            
                objecto: self
                need_image: True
                columnas: 5

                list_table_labels: ["id_imagen", "id_id", "id_proveedor", "id_cantidad", "id_gasto"]
                list_table_data: ["imagen","id", "proveedor", "cantidad", "gasto"]

                modalData: 
                    'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este producto?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","StorePageUpdate", "Almacen - Modificar"))'
                
                test: 
                    'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_id", f"dato{i}_proveedor", f"dato{i}_cantidad", f"dato{i}_gasto"]};self.objecto.DictionaryDataset.update(d)'

<SupplierPage>:
    name: "SupplierPage"

    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)

        MDGridLayout:
            cols: 1
             
            #MDGridLayout:
            #    cols: 1
            #    padding: dp(8), dp(32), dp(8), dp(8)
            #    size_hint_y: None
            #    height: self.minimum_height


            #    MDLabel:
            #        text: "Proveedores"
            #        halign: "center"
            #        font_style: "H4"

            MDGridLayout:
                cols: 5
                spacing: dp(10)
                padding: dp(16), dp(16), dp(16), dp(16)
                size_hint_y: None
                height: dp(root.manager.parent.parent.ids.toolbar.height)
                MDTextField:
                    id: ButtonMenuSearchingSupplier

                    size_hint_x: None
                    width: "100dp"

                    text: "TODO"
                    hint_text: "Tipo:"
                    icon_right: "arrow-down"

                    mode: "rectangle"
                    readonly: True 
                    focus: True

                    on_focus: if self.focus: root.CallbackMenuSupplier(self)

                MDTextField:
                    id: SearchSupplier
                    hint_text: 'Buscar proveedor'
                    icon_right: "android"
                    mode: "rectangle"

                    size_hint_x: None
                    width: "400dp"

                MDFloatingActionButton:
                    id: ButtonSearchingSupplier

                    icon: "book-search"
                    type: "standard"

                MDLabel:

                MDFloatingActionButton:
                    icon: "account-multiple-plus"
                    type: "standard"

                    on_release: root.ChangePageSupplierPage()

                    
            RecycleViewTable:

                id_table: "tableSuppliers"

                padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height / 2), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                objecto: self
                need_image: True
                columnas: 5

                list_table_labels: ["id_imagen", "id_nombre", "id_ubicacion", "id_rif", "id_telefono"]
                list_table_data: ["imagen","nombre", "ubicacion", "rif", "telefono"]

                modalData: 
                    'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este producto?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","SupplierUpdatePage", "Proveedor - Modificar"))'
                
                test: 
                    'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_nombre", f"dato{i}_ubicacion", f"dato{i}_rif", f"dato{i}_telefono"]};self.objecto.DictionaryDataset.update(d)'


<SupplierUpdatePage>:
    name: "SupplierUpdatePage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDScrollView:
            MDBoxLayout:

                orientation: 'horizontal'
                size_hint: 1, 1
                adaptive_height: True

                MDGridLayout:
                    cols: 1
                    padding: dp(16), dp(8)
                    size_hint_y: None
                    height: self.minimum_height  # required to size GridLayout

                            
                    MDGridLayout:
                        cols: 1
                        padding: dp(1), dp(32)

                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout

                        MDLabel:
                            text: "Cambiar proveedor"
                            halign: "center"
                            font_style: "H4"

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(0), dp(16), dp(8) 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Nombre:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Nombre del proveedor:"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Ubicación:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: inputSupplierMenu
                            size_hint_x: 0.7
                            #width: "375dp"
                            text: ""
                            hint_text: "Ubicación del proveedor:"
                            
                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1
                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "RIF:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "RIF del proveedor"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Teléfono:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "Teléfono del proveedor"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 2
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        
                        height: self.minimum_height  # required to size GridLayout

                        MDRectangleFlatButton:
                            size_hint_x: 0.5
                            text: "Cancelar"
                            line_color: "red"
                            text_color: "red"

                        MDRaisedButton:
                            size_hint_x: 0.5
                            text: "Modificar"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"

<SupplierAddPage>:
    name: "SupplierAddPage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDScrollView:
            MDBoxLayout:

                orientation: 'horizontal'
                size_hint: 1, 1
                adaptive_height: True

                MDGridLayout:
                    cols: 1
                    padding: dp(16), dp(8)
                    size_hint_y: None
                    height: self.minimum_height  # required to size GridLayout

                            
                    MDGridLayout:
                        cols: 1
                        padding: dp(1), dp(32)

                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout

                        MDLabel:
                            text: "Añadir proveedor"
                            halign: "center"
                            font_style: "H4"

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(0), dp(16), dp(8) 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Nombre:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Nombre del proveedor:"

                            mode: "rectangle"
                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Ubicación:"
                            halign: "right"
                            font_style: "H5"

                        
                        MDTextField:

                            id: inputSupplierMenu
                            size_hint_x: 0.7
                            #width: "375dp"
                            text: ""
                            hint_text: "Ubicación del proveedor:"
                            
                            mode: "rectangle"
                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1
                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "RIF:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "RIF del proveedor"

                            mode: "rectangle"
                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Teléfono:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "Teléfono del proveedor"
                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 2
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        
                        height: self.minimum_height  # required to size GridLayout

                        MDRectangleFlatButton:
                            size_hint_x: 0.5
                            text: "Cancelar"
                            line_color: "red"
                            text_color: "red"

                        MDRaisedButton:
                            size_hint_x: 0.5
                            text: "Agregar"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"



<MoneyHistory>:
    name: "MoneyHistory"
    
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        
        
        MDGridLayout:
            cols:1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
            
            MDGridLayout:
                cols: 2
                                          
                MDScrollView:

                    MDBoxLayout:

                        orientation: 'horizontal'
                        size_hint: 1, 1
                        adaptive_height: True
                        MDGridLayout:
                            cols: 1
                            padding: dp(16), dp(8)
                            size_hint_y: None
                            height: self.minimum_height  # required to size GridLayout

                            MDGridLayout:
                                cols: 1
                                padding: dp(1), dp(32), dp(1), dp(48)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout

                                MDLabel:
                                    id: MoneyHistoryTitle
                                    text: "MES"
                                    halign: "center"
                                    font_style: "H4"
                                

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(18)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:

                                    size_hint_x: 0.4
                                    text: "Ventas:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDLabel:

                                    id: LabelSalesProducts
                                    size_hint_x: 0.4

                                    halign: "center"

                                    text: "-XXX$"
                                    mode: "rectangle"

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(18)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:

                                    size_hint_x: 0.4
                                    text: "Encargos:"
                                    halign: "left"
                                    font_style: "H6"
                                    #md_bg_color: "red"

                                MDLabel:
                                
                                    id: LabelChargeProducts
                                    size_hint_x: 0.4

                                    halign: "center"

                                    text: "-XXX$"
                                    mode: "rectangle"

                            MDGridLayout:
                                cols: 2
                                spacing: dp(20)
                                padding: dp(16), dp(18)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                MDLabel:
                                    size_hint_x: 0.4
                                MDLabel:

                                    id: LabelTotalMoney
                                    size_hint_x: 0.4

                                    halign: "center"
                                    underline: True

                                    text: "XXX$"
                                    mode: "rectangle"

                MDBoxLayout:
                    orientation: 'vertical'
                    size_hint: 1, 1
                    padding: dp(1), dp(16), dp(1), dp(1)
                    #spacing: dp(-60)

                    MDGridLayout:
                        cols:1

                        
                        AnchorLayout:
                            anchor_x:'center'
                            anchor_y:'top'

                            MDRaisedButton:
                                text: "Elegir fecha"
                                font_style: "H5"

                                on_release: app.datePicker.show_date_picker()  

                           

                        AnchorLayout:
                            anchor_x:'center'
                            anchor_y:'center'

                            MDRaisedButton:
                                id: buttonChangeTypeMoneyHistory
                                text: "Cambiar a: TOTAL"
                                font_style: "H5"
                                on_release: root.ChangeTypeHistoryMoney()  



            MDScrollView:
                MDGridLayout:
                    cols: 1
                    
                    #MDGridLayout:
                    #    cols: 1
                    #    padding: dp(8), dp(32), dp(8), dp(8)
                    size_hint_y: None
                    height: self.minimum_height


                    #    MDLabel:
                    #        text: "Proveedores"
                    #        halign: "center"
                    #        font_style: "H4"
                    MDGridLayout:
                        cols: 5
                        spacing: dp(10)
                        padding: dp(16), dp(1)
                        size_hint_y: None
                        height: dp(root.manager.parent.parent.ids.toolbar.height)
                        MDTextField:
                            id: ButtonMenuSearchingMoneyHistory

                            size_hint_x: None
                            width: "100dp"

                            text: "TODO"
                            hint_text: "Tipo:"
                            icon_right: "arrow-down"

                            mode: "rectangle"
                            readonly: True 
                            focus: True

                            #on_focus: if self.focus: root.CallbackMenuSupplier(self)

                        MDTextField:
                            id: SearchMoneyHistory
                            hint_text: 'Buscar historial de dinero'
                            icon_right: "android"
                            mode: "rectangle"

                            size_hint_x: None
                            width: "400dp"

                        MDFloatingActionButton:
                            id: ButtonSearchingMoneyHistory

                            icon: "book-search"
                            type: "standard"

                        MDLabel:

                        MDFloatingActionButton:
                            icon: "account-multiple-plus"
                            type: "standard"

                    
                    RecycleViewTable:
                    
                        id_table: "tableMoneyHistory"

                        size_hint_y: None
                        height: dp(400)
                        padding: dp(16), dp(16), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                        objecto: self
                        need_image: True
                        columnas: 5

                        list_table_labels: ["id_imagen", "id_dado", "id_fecha", "id_monto"]
                        list_table_data: ["imagen","dado por", "fecha", "monto"]

                        dictionaryPrincipal: ["_nombre", "_proveedor", "_cantidad", "_precio"]
                        
                        modalData: 
                            'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este producto?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","StorePageUpdate", "Almacen - Modificar"))'
                        
                        test: 
                            'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_dado", f"dato{i}_fecha", f"dato{i}_monto"]};self.objecto.DictionaryDataset.update(d)'

<LoanPage>:

    name: "LoanPage"
    
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 1, 1
        
        
        MDGridLayout:
            cols:1
            padding: dp(16), dp(root.manager.parent.parent.ids.toolbar.height), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height)
            
            MDGridLayout:
                cols: 2
                                          
                MDScrollView:

                    MDBoxLayout:

                        orientation: 'horizontal'
                        size_hint: 1, 1
                        adaptive_height: True
                        MDGridLayout:
                            cols: 1
                            padding: dp(16), dp(8)
                            size_hint_y: None
                            height: self.minimum_height  # required to size GridLayout

                            MDGridLayout:
                                cols: 1
                                padding: dp(1), dp(32), dp(1), dp(48)

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout

                                MDLabel:
                                    id: MoneyHistoryTitle
                                    text: "MES"
                                    halign: "center"
                                    font_style: "H4"

                            
                            MDGridLayout:
                                id: gridLayoutLoanItems
                                cols: 1

                                size_hint_y: None
                                height: self.minimum_height  # required to size GridLayout
                                
                                #AQUI APARECERAN OJO
                MDBoxLayout:
                    orientation: 'vertical'
                    size_hint: 1, 1
                    padding: dp(1), dp(16), dp(1), dp(1)
                    #spacing: dp(-60)

                    MDGridLayout:
                        cols:1

                        
                        AnchorLayout:
                            anchor_x:'center'
                            anchor_y:'top'

                            MDRaisedButton:
                                text: "Elegir fecha"
                                font_style: "H5"

                                on_release: app.datePicker.show_date_picker()  

                           

                        AnchorLayout:
                            anchor_x:'center'
                            anchor_y:'center'

                            MDRaisedButton:
                                id: buttonChangeTypeMoneyHistory
                                text: "Cambiar a: TOTAL"
                                font_style: "H5"
                                on_release: root.ChangeItemsGrid('total') if self.text == 'Cambiar a: TOTAL' else root.ChangeItemsGrid('mes')



            MDScrollView:
                MDGridLayout:
                    cols: 1
                    
                    #MDGridLayout:
                    #    cols: 1
                    #    padding: dp(8), dp(32), dp(8), dp(8)
                    size_hint_y: None
                    height: self.minimum_height


                    #    MDLabel:
                    #        text: "Proveedores"
                    #        halign: "center"
                    #        font_style: "H4"
                    MDGridLayout:
                        cols: 5
                        spacing: dp(10)
                        padding: dp(16), dp(1)
                        size_hint_y: None
                        height: dp(root.manager.parent.parent.ids.toolbar.height)
                        MDTextField:
                            id: ButtonMenuSearchingMoneyHistory

                            size_hint_x: None
                            width: "100dp"

                            text: "TODO"
                            hint_text: "Tipo:"
                            icon_right: "arrow-down"

                            mode: "rectangle"
                            readonly: True 
                            focus: True

                            #on_focus: if self.focus: root.CallbackMenuSupplier(self)

                        MDTextField:
                            id: SearchMoneyHistory
                            hint_text: 'Buscar historial de dinero'
                            icon_right: "android"
                            mode: "rectangle"

                            size_hint_x: None
                            width: "400dp"

                        MDFloatingActionButton:
                            id: ButtonSearchingMoneyHistory

                            icon: "book-search"
                            type: "standard"

                        MDLabel:

                        MDFloatingActionButton:
                            icon: "account-multiple-plus"
                            type: "standard"

                            on_release: root.ChangePageLoanPage()

                    
                    RecycleViewTable:
                    
                        id_table: "tableLoan"

                        size_hint_y: None
                        height: dp(400)
                        padding: dp(16), dp(16), dp(16), dp(root.manager.parent.parent.ids.toolbarbottom.height /2)

                        objecto: self
                        need_image: True
                        columnas: 5

                        list_table_labels: ["id_imagen", "id_dado", "id_fecha", "id_monto"]
                        list_table_data: ["imagen","dado por", "fecha", "monto"]

                        modalData: 
                            'ModalsDialog.ShowAlertDialog("self","¿Que desea realizar?","Por favor, elija algunas de las opciones presentadas.","Cancelar","Eliminar","Modificar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog.dismiss()),lambda x: ModalsDialog.ShowAlertDialogDelete("self","¿De verdad quiere eliminar este prestamo?","Si es así, adelante","Cancelar","Eliminar",lambda x: ModalsDialog.CloseDialog("self", RecycleViewTable.dialog2.dismiss()),lambda x: print("cerrar")),lambda x: ModalsDialog.ChangePage("self","LoanUpdatePage", "Prestamo - Modificar"))'
                        
                        test: 
                            'for i in range(1,5): d = {f"dato{i}": [f"images/logo.jpg", f"dato{i}_dado", f"dato{i}_fecha", f"dato{i}_monto"]};self.objecto.DictionaryDataset.update(d)'


<LoanUpdatePage>:
    name: "LoanUpdatePage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDScrollView:
            MDBoxLayout:

                orientation: 'horizontal'
                size_hint: 1, 1
                adaptive_height: True

                MDGridLayout:
                    cols: 1
                    padding: dp(16), dp(8)
                    size_hint_y: None
                    height: self.minimum_height  # required to size GridLayout

                            
                    MDGridLayout:
                        cols: 1
                        padding: dp(1), dp(32)

                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout

                        MDLabel:
                            text: "Cambiar Prestamo"
                            halign: "center"
                            font_style: "H4"

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(0), dp(16), dp(8) 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Dado por:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Dado por el empleado:"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Fecha:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: inputSupplierMenu
                            size_hint_x: 0.7
                            #width: "375dp"
                            text: ""
                            hint_text: "Fecha realizada:"
                            
                            mode: "rectangle"

                            on_focus: if self.focus: app.datePicker.show_date_picker() 
                        
                        MDLabel:
                            size_hint_x: 0.1
                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Monto:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "Monto del prestamo"

                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 2
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        
                        height: self.minimum_height  # required to size GridLayout

                        MDRectangleFlatButton:
                            size_hint_x: 0.5
                            text: "Cancelar"
                            line_color: "red"
                            text_color: "red"

                        MDRaisedButton:
                            size_hint_x: 0.5
                            text: "Modificar"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"


<LoanAddPage>:
    name: "LoanAddPage"
                
    MDBoxLayout:

        padding: dp(1), dp(root.manager.parent.parent.ids.toolbar.height), dp(1), dp(root.manager.parent.parent.ids.toolbarbottom.height)
        
        MDScrollView:
            MDBoxLayout:

                orientation: 'horizontal'
                size_hint: 1, 1
                adaptive_height: True

                MDGridLayout:
                    cols: 1
                    padding: dp(16), dp(8)
                    size_hint_y: None
                    height: self.minimum_height  # required to size GridLayout

                            
                    MDGridLayout:
                        cols: 1
                        padding: dp(1), dp(32)

                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout

                        MDLabel:
                            text: "Cambiar Prestamo"
                            halign: "center"
                            font_style: "H4"

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(0), dp(16), dp(8) 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Dado por:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7
                            #width: "375dp"

                            hint_text: "Dado por el empleado:"
                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"


                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        #padding: ["16dp", "16dp", "16dp", "16dp"]  if len(inputSupplierMenu.text) == 0 else ["16dp", "8dp", "16dp", "8dp"] 
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Fecha:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: inputSupplierMenu
                            size_hint_x: 0.7
                            #width: "375dp"
                            text: ""
                            hint_text: "Fecha realizada:"

                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"

                            
                            mode: "rectangle"

                            on_focus: if self.focus: app.datePicker.show_date_picker() 
                        
                        MDLabel:
                            size_hint_x: 0.1
                    MDGridLayout:
                        cols: 3
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        height: self.minimum_height  # required to size GridLayout
                        MDLabel:
                            size_hint_x: 0.38
                            #width: "250dp"
                            padding: dp(32), dp(1)

                            text: "Monto:"
                            halign: "right"
                            font_style: "H5"
                        
                        MDTextField:

                            id: name_field
                            size_hint_x: 0.7

                            hint_text: "Monto del prestamo"

                            required: True
                            line_color_normal: "red" if len(self.text) == 0 else "blue"


                            mode: "rectangle"
                        
                        MDLabel:
                            size_hint_x: 0.1

                    MDGridLayout:
                        cols: 2
                        spacing: dp(20)
                        padding: dp(16), dp(8)
                        size_hint_y: None
                        
                        height: self.minimum_height  # required to size GridLayout

                        MDRectangleFlatButton:
                            size_hint_x: 0.5
                            text: "Cancelar"
                            line_color: "red"
                            text_color: "red"

                        MDRaisedButton:
                            size_hint_x: 0.5
                            text: "Agregar"
                            text_color: "white"
                            line_color: "blue"
                            md_bg_color: "blue"


<SignIn>:
    name: "SignIn"


    MDBoxLayout:
        orientation: 'horizontal'
        padding: dp(100)

        MDGridLayout:
            cols: 1

            MDLabel:
                text: 'INICIAR SESION'
                font_style: "H3"
                halign: 'center'
                adaptive_height: True
            
            MDGridLayout:
                cols: 1
                padding: dp(50)
                spacing: dp(20)
                adaptive_height: True

                MDTextField:
                    icon_left: "key-variant"
                    hint_text: 'Escribir nombre de usuario'
                    mode: 'rectangle'

                MDTextField:
                    icon_left: "key-variant"
                    hint_text: 'Escribir contraseña'
                    mode: 'rectangle'
                    password: True
            
            MDGridLayout:
                cols: 3
                spacing: dp(20)
                adaptive_height: True
                padding: dp(16), dp(32), dp(16), dp(8)

                MDRectangleFlatButton:
                    text: 'Crear cuenta'
                    font_style: 'H5'
                    size_hint_x: 0.4

                    on_release: root.ChangePageToSignOn()

                MDLabel:
                    size_hint_x: 0.1

                MDRaisedButton:
                    text: 'Enviar'
                    font_style: 'H5'
                    size_hint_x: 0.4

                    on_release: root.OpenSystem('self')


<SignOn>:
    name: "SignOn"

    MDScrollView:
        MDBoxLayout:
            adaptive_height: True
            orientation: 'horizontal'
            padding: dp(100)

            MDGridLayout:
                cols: 1
                adaptive_height: True

                MDLabel:
                    text: 'REGISTRAR CUENTA'
                    font_style: "H3"
                    halign: 'center'
                    adaptive_height: True
                
                MDGridLayout:
                    cols: 1
                    padding: dp(50)
                    spacing: dp(20)
                    adaptive_height: True

                    MDTextField:
                        icon_left: "key-variant"
                        hint_text: 'Escribir nombre de usuario'
                        mode: 'rectangle'

                    MDTextField:
                        icon_left: "key-variant"
                        hint_text: 'Escribir correo electrónico'
                        mode: 'rectangle'
                        validator: "email"

                    MDTextField:
                        icon_left: "key-variant"
                        hint_text: 'Escribir contraseña'
                        mode: 'rectangle'
                        password: True
                    
                    MDTextField:
                        icon_left: "key-variant"
                        hint_text: 'Repetir contraseña'
                        mode: 'rectangle'
                        password: True
                
                MDGridLayout:
                    cols: 3
                    spacing: dp(20)
                    adaptive_height: True
                    padding: dp(16), dp(32), dp(16), dp(8)

                    MDRectangleFlatButton:
                        text: 'Iniciar sesión'
                        font_style: 'H5'
                        size_hint_x: 0.4

                        on_release: root.ChangePageToSignIn()

                    MDLabel:
                        size_hint_x: 0.1

                    MDRaisedButton:
                        text: 'Enviar'
                        font_style: 'H5'
                        size_hint_x: 0.4

                        #on_release: root.OpenSystem('self')




